"""empty message

Revision ID: 155b4aadb078
Revises: 
Create Date: 2021-10-31 13:40:46.733951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155b4aadb078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cpf_or_cnpj', sa.String(length=16), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('legal_person', sa.Boolean(), nullable=True),
    sa.Column('spouse_id', sa.Integer(), nullable=True),
    sa.Column('birth_file', sa.String(length=200), nullable=True),
    sa.Column('wedding_file', sa.String(length=200), nullable=True),
    sa.Column('residence_file', sa.String(length=200), nullable=True),
    sa.Column('income_tax_file', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['spouse_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_or_cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('clients')
    # ### end Alembic commands ###
