"""empty message

Revision ID: 3e540e2cedca
Revises: 
Create Date: 2021-10-30 15:35:04.541912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e540e2cedca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('cpf', sa.String(length=16), nullable=False),
    sa.Column('legal_person', sa.Boolean(), nullable=True),
    sa.Column('document', sa.String(length=200), nullable=False),
    sa.Column('document2', sa.String(length=200), nullable=False),
    sa.Column('document3', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('cep'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('document'),
    sa.UniqueConstraint('document2'),
    sa.UniqueConstraint('document3'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('clients')
    # ### end Alembic commands ###
