"""empty message

Revision ID: da6f3e178719
Revises: 
Create Date: 2021-10-31 21:52:55.555943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6f3e178719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spouse',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('cpf_or_cnpj', sa.String(length=16), nullable=False),
    sa.Column('legal_person', sa.Boolean(), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('income_tax_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_or_cnpj')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cpf_or_cnpj', sa.String(length=16), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('legal_person', sa.Boolean(), nullable=True),
    sa.Column('patrimony', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('spouse_id', sa.Integer(), nullable=True),
    sa.Column('birth_file', sa.String(length=200), nullable=False),
    sa.Column('wedding_file', sa.String(length=200), nullable=True),
    sa.Column('residence_file', sa.String(length=200), nullable=False),
    sa.Column('income_tax_file', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['spouse_id'], ['spouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_or_cnpj'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=84), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cpf_or_cnpj_situation', sa.Boolean(), nullable=True),
    sa.Column('company_creation_date', sa.String(length=84), nullable=True),
    sa.Column('serasa_score', sa.Integer(), nullable=True),
    sa.Column('serasa_pendency', sa.String(length=84), nullable=False),
    sa.Column('final_approve', sa.String(length=84), nullable=False),
    sa.Column('risk_level', sa.String(length=84), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('requests')
    op.drop_table('users')
    op.drop_table('clients')
    op.drop_table('spouse')
    op.drop_table('groups')
    # ### end Alembic commands ###
